version: "3"
services:
### mysql ###
  mysql:
    image: mysql:${MYSQL_VERSION}
    networks:
      - lnmpnet
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PWD}
    volumes:
      - ${MYSQL_LOGS_PATH}:/logs
      - ${MYSQL_DATA_PATH}:/data
      - ${MYSQL_CNF_PATH}:/etc/mysql/my.cnf
    ports:
      - "${MYSQL_PORT}:3306"
### redis ###
  redis:
    image: redis:${REDIS_VERSION}
    volumes:
      - ${REDIS_DATA}:/data
    networks:
      - lnmpnet
    ports:
      - "${REDIS_PORT}:6379"
### MongoDb ###
  mongo:
    image: mongo:${MONGO_VERSION}
    ports:
      - "${MONGO_HOST_PORT}:27017"
    volumes:
      - ${MONGO_DATA_DB_DIR}:/data/db
    networks:
      - lnmpnet
### hyperf env ###
  hyperf:
    build:
      context: ./hyperf
    volumes:
      - ${APPLICATION}:/www
      - ${HYPERF_INI_PATH}:/usr/local/etc/php/php.ini
      - ${HYPERF_LOGS_PATH}:/logs
    networks:
      - lnmpnet
### php7.2 fpm ###
  php-fpm72:
    build:
      context: ./php72
      args:
        - INSTALL_AMQP=${INSTALL_AMQP}
        - INSTALL_SWOOLE=${INSTALL_SWOOLE}
        - INSTALL_PHPREDIS=${INSTALL_PHPREDIS}
        - INSTALL_IMAGEMAGICK=${INSTALL_IMAGEMAGICK}
        - INSTALL_MONGO=${INSTALL_TIDEWAYS_XHPROF}
        - INSTALL_TIDEWAYS_XHPROF=${INSTALL_TIDEWAYS_XHPROF}
    volumes:
      - ${APPLICATION}:/www
      - ${PHP72_INI_PATH}:/usr/local/etc/php/php.ini
      - ${PHP72_LOGS_PATH}:/phplogs
    networks:
      - lnmpnet
    ports:
      - "${PHP72_FPM_PORT}:9000"
### php56 fpm ###
  php-fpm56:
    build:
      context: ./php56
      args:
        - INSTALL_SWOOLE=${INSTALL_SWOOLE}
        - INSTALL_PHPREDIS=${INSTALL_PHPREDIS}
        - INSTALL_IMAGEMAGICK=${INSTALL_IMAGEMAGICK}
    volumes:
      - ${APPLICATION}:/www
      - ${PHP56_INI_PATH}:/usr/local/etc/php/php.ini
      - ${PHP56_LOGS_PATH}:/phplogs
    networks:
      - lnmpnet
    ports:
      - "${PHP56_FPM_PORT}:9000"
### nginx ###
  nginx:
    image: nginx:${NGINX_TAG}
    networks:
      - lnmpnet
    volumes:
      - ${APPLICATION}:/www
      - ${NGINX_CONFD_DIR}:/etc/nginx/conf.d
      - ${NGINX_LOGS_PATH}:/wwwlogs
      - ${NGINX_CONF_PATH}:/etc/nginx/nginx.conf
      - ${NGINX_SSL_PATH}:/etc/nginx/ssl
    ports:
      - "${NGINX_HTTP_PORT}:80"
      - "${NGINX_HTTPS_PORT}:443"
 ####Gogs###
  gogs:
    image: gogs/gogs
    networks:
      - lnmpnet
    volumes:
      - ${GOGS_DATA_PATH}:/data
    ports:
      - "${GOGS_PORT}:3000"
### RabbitMQ ###
  rabbitmq:
    build: ./rabbitmq
    ports:
      - "${RABBITMQ_HOST_PORT}:5672"
      - "${RABBITMQ_MANAGEMENT_HTTP_HOST_PORT}:15672"
      - "${RABBITMQ_MANAGEMENT_HTTPS_HOST_PORT}:15671"
    privileged: true
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    depends_on:
      - php-fpm72
    volumes:
      - $PWD/rabbitmq/data:/var/lib/rabbitmq
    networks:
      - lnmpnet
### ElasticSearch ###
  elasticsearch:
    build:
      context: ./elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - $PWD/elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - "${ELASTICSEARCH_HOST_HTTP_PORT}:9200"
      - "${ELASTICSEARCH_HOST_TRANSPORT_PORT}:9300"
    depends_on:
      - php-fpm72
    networks:
      - lnmpnet
### ElasticSearch-head ###
  es-head:
    image: mobz/elasticsearch-head:5
    volumes:
      - $PWD/elasticsearch/plugins/head/_site:/usr/src/app/_site
    ports:
      - "${ELASTICSEARCH_HEAD_PORT}:9100"
    depends_on:
      - elasticsearch
    networks:
      - lnmpnet
###tideways###
  tideways:
    build: ./tideways
    networks:
      - lnmpnet
    ports:
      - "9135:9135"
      - "8135:8135"
networks:
  lnmpnet:
    external: false
